import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import WidthWrapper from "@/components/width-wrapper";
import Navbar from "@/components/navbar";

const manRope = Manrope({
  subsets: ['latin'],
  weight: "400"
});

export const metadata: Metadata = {
  title: "vinayisactive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manRope.className}`} >
        <WidthWrapper>
            <Navbar/>
              {children}
        </WidthWrapper>
      </body>
    </html>
  );
}
